fid = fopen('hamlet.txt', 'r');
hamlet = fread(fid)';
fclose(fid);
%char(hamlet(1:1000));
p = hist(hamlet,0:255);
p = p/sum(p);
nonzero = find(p);
t = code2tree(c(nonzero,:),cl(nonzero));
%lowercase = find(hamlet>='a' & hamlet<='z');
%hamlet_uppercase = hamlet;
%hamlet_uppercase(lowercase) = hamlet_uppercase(lowercase)-'a'+'A';
%P = hist(hamlet_uppercase,0:255);
%P = P/sum(P);
%NONZERO = find(P);
[c,cl] = shannon_fano(p);
%T = code2tree(c(NONZERO,:),cl(NONZERO));
%hamlet_bin = vl_encode(hamlet_uppercase,c,cl,0:255);
%length(hamlet_bin);
%hamlet_cz1 = bits2bytes(hamlet_bin);
%length(hamlet_cz1);
